rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: aws_rds_acuutilization_average{namespace="rhacs-1234", dimension_DBInstanceIdentifier="rhacs-test-db-instance"}
        values: "50x10 100x70"
    alert_rule_test:
      - eval_time: 10m
        alertname: AWSRDSACUUtilization
        exp_alerts: []
      - eval_time: 85m
        alertname: AWSRDSACUUtilization
        exp_alerts:
          - exp_labels:
              alertname: AWSRDSACUUtilization
              dimension_DBInstanceIdentifier: rhacs-test-db-instance
              namespace: rhacs-1234
              severity: critical
            exp_annotations:
              summary: "The AWS RDS ACUUtilization for `rhacs-test-db-instance` DB instance is too high."
              description: >
                The DB instance `rhacs-test-db-instance` has scaled up as high as it can.
                Consider increasing the maximum ACU setting for the cluster.
              sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-014-aws-rds-acu-utilization.md"
