rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: namespace_workload_pod:kube_pod_owner:relabel{namespace="rhacs",workload="operator-workload",pod="operator-pod"}
        values: "1+0x20"
      - series: kube_pod_labels{namespace="rhacs",label_app="rhacs-operator",pod="operator-pod"}
        values: "1+0x20"
      - series: container_memory_max_usage_bytes{namespace="rhacs", pod="operator-pod",container="manager"}
        values: "50+0x10 70+0x10"
      - series: container_spec_memory_limit_bytes{namespace="rhacs",pod="operator-pod",container="manager"}
        values: "100+0x20"
    alert_rule_test:
      - eval_time: 1m
        alertname: RHACSOperatorMemoryUtilizationHigh
        exp_alerts: []
      - eval_time: 16m
        alertname: RHACSOperatorMemoryUtilizationHigh
        exp_alerts:
          - exp_labels:
              alertname: RHACSOperatorMemoryUtilizationHigh
              severity: warning
              namespace: rhacs
              workload: operator-workload
              container: manager
            exp_annotations:
              description: The container 'manager' in operator 'operator-workload' reached 70% of its memory limit and is at risk of being OOM killed.
              summary: "The container 'manager' in operator 'operator-workload' is reaching its memory limit."
              sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-037-operator-memory-high.md"
  - interval: 1m
    input_series:
      - series: namespace_workload_pod:kube_pod_owner:relabel{namespace="rhacs",workload="operator-workload",pod="operator-pod"}
        values: "1+0x20"
      - series: kube_pod_labels{namespace="rhacs",label_app="rhacs-operator",pod="operator-pod"}
        values: "1+0x20"
      - series: container_memory_max_usage_bytes{namespace="rhacs", pod="operator-pod",container="manager"}
        values: "50+0x10 91+0x10"
      - series: container_spec_memory_limit_bytes{namespace="rhacs",pod="operator-pod",container="manager"}
        values: "100+0x20"
    alert_rule_test:
      - eval_time: 1m
        alertname: RHACSOperatorMemoryUtilizationCritical
        exp_alerts: []
      - eval_time: 17m
        alertname: RHACSOperatorMemoryUtilizationCritical
        exp_alerts:
          - exp_labels:
              alertname: RHACSOperatorMemoryUtilizationCritical
              severity: critical
              namespace: rhacs
              workload: operator-workload
              container: manager
            exp_annotations:
              description: The container 'manager' in operator 'operator-workload' reached 91% of its memory limit and is at high risk of being OOM killed.
              summary: The container 'manager' in operator 'operator-workload' is critically reaching its memory limit.
              sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-037-operator-memory-high.md"
