rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1d
    input_series:
      - series: acs_fleetshard_certificate_expiration_timestamp{namespace="rhacs", secret="secret", data_key="key"}
        values: "691200+0x15" # equals to 8 days

    alert_rule_test:
      - eval_time: 0
        alertname: RHACSFleetshardCertificateExpiringSoon
        exp_alerts: [ ]
      - eval_time: 3d
        alertname: RHACSFleetshardCertificateExpiringSoon
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiringSoon
              namespace: rhacs
              secret: secret
              data_key: key
              severity: warning
            exp_annotations:
              summary: "Certificate Expiring soon in namespace `rhacs` for secret 'secret'."
              description: "Certificate `key` in namespace `rhacs` is expiring in less than 7 days, on '1970-01-09 00:00:00 +0000 UTC'."
      - eval_time: 7d
        alertname: RHACSFleetshardCertificateExpiringCritical
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiringCritical
              namespace: rhacs
              secret: secret
              data_key: key
              severity: critical
            exp_annotations:
              summary: "Certificate expiring very soon: 'rhacs/secret/key`."
              description: "Certificate 'rhacs/secret/key` expires on '1970-01-09 00:00:00 +0000 UTC'."
      - eval_time: 10d
        alertname: RHACSFleetshardCertificateExpiringCritical
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiringCritical
              namespace: rhacs
              secret: secret
              data_key: key
              severity: critical
            exp_annotations:
              summary: "Certificate expiring very soon: 'rhacs/secret/key`."
              description: "Certificate 'rhacs/secret/key` expires on '1970-01-09 00:00:00 +0000 UTC'."
