rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: acs_fleetshard_certificate_expiration_timestamp{namespace="rhacs", secret="secret-1", data_key="key-1"}
        values: "700000" #future example
      - series: acs_fleetshard_certificate_expiration_timestamp{namespace="rhacs", secret="secret-critical", data_key="key-critical"}
        values:  "80000" #less than 1 day
    alert_rule_test:
      - eval_time: 15m
        alertname: RHACSFleetshardCertificateExpiringCritical
        exp_alerts: []
      - eval_time: 15m
        alertname: RHACSFleetshardCertificateExpiringCritical
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiringCritical
              namespace: rhacs
              secret: secret-critical
              data_key: key-critical
              severity: critical
            exp_annotations:
              summary: "Certificate Expiring very soon in namespace `rhacs` for secret 'secret-critical'."
              description: "Certificate `key-critical` in namespace `rhacs` is expiring in less than a day."