rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: kube_pod_container_status_restarts_total{namespace="rhacs", pod="emailsender-123", container="emailsender"}
        values: "0+0x30 1+1x10 4+1x20"
    alert_rule_test:
      - eval_time: 30m
        alertname: RHACSEmailsenderContainerFrequentlyRestarting
        exp_alerts: []
      - eval_time: 60m
        alertname: RHACSEmailsenderContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: RHACSEmailsenderContainerFrequentlyRestarting
              container: emailsender
              namespace: rhacs
              pod: emailsender-123
              severity: warning
            exp_annotations:
              summary: "Email Sender container `emailsender-123/emailsender` in namespace `rhacs` restarted more than 3 times."
              description: "Email Sender container `emailsender-123/emailsender` in namespace `rhacs` has restarted more than 3 times during the last 30 minutes."
              sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-046-emailsender-unavailable.md"
