rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: kubelet_volume_stats_available_bytes{persistentvolumeclaim="stackrox-db", namespace="rhacs-1234"}
        # Initial time series value is 10GiB, it is decremented by 100MiB every minute for 360 minutes.
        values: "10737418240+0x10 10737418240-104857600x110"
      - series: kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="stackrox-db", namespace="rhacs-1234"}
        values: "10737418240+0x120"
    alert_rule_test:
      - eval_time: 10m
        alertname: RHACSCentralDatabasePersistentVolumeFillingUp
        exp_alerts: []
      - eval_time: 100m
        alertname: RHACSCentralDatabasePersistentVolumeFillingUp
        exp_alerts:
          - exp_labels:
              alertname: RHACSCentralDatabasePersistentVolumeFillingUp
              severity: warning
              persistentvolumeclaim: stackrox-db
              namespace: rhacs-1234
            exp_annotations:
              summary: "Central database storage in namespace `rhacs-1234` is filing up."
              description: "Central database storage in namespace `rhacs-1234` is filling up for PVC `stackrox-db`. Available storage quota is `13.09%`. The volume is expected to fill up within 4 days based on linear extrapolation over the last 6 hours."
              sop_url: "https://github.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-006-increasing-rhacs-pvc-size.md"
      - eval_time: 110m
        alertname: RHACSCentralDatabasePersistentVolumeFillingUp
        exp_alerts:
          - exp_labels:
              alertname: RHACSCentralDatabasePersistentVolumeFillingUp
              severity: critical
              persistentvolumeclaim: stackrox-db
              namespace: rhacs-1234
            exp_annotations:
              summary: "Central database storage in namespace `rhacs-1234` is filing up."
              description: "Central database storage in namespace `rhacs-1234` is filling up for PVC `stackrox-db`. Available storage quota is `3.32%`."
              sop_url: "https://github.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-006-increasing-rhacs-pvc-size.md"
          - exp_labels:
              alertname: RHACSCentralDatabasePersistentVolumeFillingUp
              severity: warning
              persistentvolumeclaim: stackrox-db
              namespace: rhacs-1234
            exp_annotations:
              summary: "Central database storage in namespace `rhacs-1234` is filing up."
              description: "Central database storage in namespace `rhacs-1234` is filling up for PVC `stackrox-db`. Available storage quota is `3.32%`. The volume is expected to fill up within 4 days based on linear extrapolation over the last 6 hours."
              sop_url: "https://github.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-006-increasing-rhacs-pvc-size.md"
