rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: kube_pod_container_status_ready{namespace="rhacs", pod="fleetshard-sync-1234", container="fleetshard-sync"}
        values: "1+0x5 0+0x25"
    alert_rule_test:
      - eval_time: 5m
        alertname: RHACSFleetshardSyncContainerDown
        exp_alerts: []
      - eval_time: 16m
        alertname: RHACSFleetshardSyncContainerDown
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardSyncContainerDown
              container: fleetshard-sync
              namespace: rhacs
              pod: fleetshard-sync-1234
              severity: critical
            exp_annotations:
              summary: "Fleetshard synchronizer container `fleetshard-sync-1234/fleetshard-sync` in namespace `rhacs` is down or in a CrashLoopBackOff status."
              description: "Fleetshard synchronizer container `fleetshard-sync-1234/fleetshard-sync` in namespace `rhacs` has been down or in a CrashLoopBackOff status for at least 5 minutes."
              sop_url: ""
