rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: kube_pod_container_status_restarts_total{namespace="rhacs", pod="rhacs-operator-1234", container="manager"}
        values: "0+0x30 1+1x10 4+1x20"
      - series: kube_pod_container_status_restarts_total{namespace="rhacs", pod="rhacs-operator-1234", container="kube-rbac-proxy"}
        values: "0+0x30 1+1x10 4+1x20"
    alert_rule_test:
      - eval_time: 30m
        alertname: RHACSFleetshardOperatorContainerFrequentlyRestarting
        exp_alerts: []
      - eval_time: 60m
        alertname: RHACSFleetshardOperatorContainerFrequentlyRestarting
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardOperatorContainerFrequentlyRestarting
              container: manager
              namespace: rhacs
              pod: rhacs-operator-1234
              severity: critical
            exp_annotations:
              summary: "Fleetshard operator container `rhacs-operator-1234/manager` in namespace `rhacs` restarted more than 3 times."
              description: "Fleetshard operator container `rhacs-operator-1234/manager` in namespace `rhacs` has restarted more than 3 times during the last 30 minutes."
              sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-011-rhacs-operator-unavailable.md"
          - exp_labels:
              alertname: RHACSFleetshardOperatorContainerFrequentlyRestarting
              container: kube-rbac-proxy
              namespace: rhacs
              pod: rhacs-operator-1234
              severity: critical
            exp_annotations:
              summary: "Fleetshard operator container `rhacs-operator-1234/kube-rbac-proxy` in namespace `rhacs` restarted more than 3 times."
              description: "Fleetshard operator container `rhacs-operator-1234/kube-rbac-proxy` in namespace `rhacs` has restarted more than 3 times during the last 30 minutes."
              sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-011-rhacs-operator-unavailable.md"
