rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1d
    input_series:
      - series: acs_fleetshard_certificate_expiration_timestamp{exported_namespace="rhacs-00000000000000000000", secret="secret", data_key="key"}
        values: "691200+0x15" # equals to 8 days

    alert_rule_test:
      - eval_time: 0
        alertname: RHACSFleetshardCertificateExpiryWarning
        exp_alerts: [ ]
      - eval_time: 3d
        alertname: RHACSFleetshardCertificateExpiryWarning
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiryWarning
              exported_namespace: rhacs-00000000000000000000
              secret: secret
              data_key: key
              severity: warning
            exp_annotations:
              summary: "Certificate expiring soon: `rhacs-00000000000000000000/secret/key`."
              description: "Certificate `rhacs-00000000000000000000/secret/key` expires on 1970-01-09 00:00:00 +0000 UTC."
      - eval_time: 7d
        alertname: RHACSFleetshardCertificateExpiryCritical
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiryCritical
              exported_namespace: rhacs-00000000000000000000
              secret: secret
              data_key: key
              severity: critical
            exp_annotations:
              summary: "Certificate expiring very soon: `rhacs-00000000000000000000/secret/key`."
              description: "Certificate `rhacs-00000000000000000000/secret/key` expires on 1970-01-09 00:00:00 +0000 UTC."
      - eval_time: 10d
        alertname: RHACSFleetshardCertificateExpiryCritical
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardCertificateExpiryCritical
              exported_namespace: rhacs-00000000000000000000
              secret: secret
              data_key: key
              severity: critical
            exp_annotations:
              summary: "Certificate expiring very soon: `rhacs-00000000000000000000/secret/key`."
              description: "Certificate `rhacs-00000000000000000000/secret/key` expires on 1970-01-09 00:00:00 +0000 UTC."
