rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: up{namespace="rhacs-1234", pod="central-1234-5678", instance="1.2.3.4:9090"}
        values: "0+0x4 1+0x6"
      - series: kube_pod_container_status_ready{namespace="rhacs-1234", pod="central-1234-5678", container="central"}
        values: "1+0x10"
    alert_rule_test:
      - eval_time: 3m
        alertname: RHACSCentralScrapeFailed
        exp_alerts: []
      - eval_time: 5m
        alertname: RHACSCentralScrapeFailed
        exp_alerts:
          - exp_labels:
              alertname: RHACSCentralScrapeFailed
              instance: 1.2.3.4:9090
              namespace: rhacs-1234
              pod: central-1234-5678
              severity: critical
            exp_annotations:
              summary: "Prometheus unable to scrape metrics from target `central-1234-5678` in namespace `rhacs-1234`."
              description: "During the last 3 minutes, only `25%` of scrapes of target `central-1234-5678` in namespace `rhacs-1234` were successful. This alert is raised when less than 50% of scrapes are successful."
              sop_url: ""
