rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: kube_pod_container_status_ready{namespace="rhacs", pod="rhacs-operator-controller-manager-1234", container="manager"}
        values: "1+0x5 0+0x25"
      - series: kube_pod_container_status_ready{namespace="rhacs", pod="rhacs-operator-controller-manager-1234", container="kube-rbac-proxy"}
        values: "1+0x5 0+0x25"
    alert_rule_test:
      - eval_time: 5m
        alertname: RHACSFleetshardOperatorContainerDown
        exp_alerts: []
      - eval_time: 16m
        alertname: RHACSFleetshardOperatorContainerDown
        exp_alerts:
          - exp_labels:
              alertname: RHACSFleetshardOperatorContainerDown
              container: manager
              namespace: rhacs
              pod: rhacs-operator-controller-manager-1234
              severity: critical
            exp_annotations:
              summary: "Fleetshard operator container `rhacs-operator-controller-manager-1234/manager` in namespace `rhacs` is down or in a CrashLoopBackOff status."
              description: "Fleetshard operator container `rhacs-operator-controller-manager-1234/manager` in namespace `rhacs` has been down or in a CrashLoopBackOff status for at least 5 minutes."
              sop_url: ""
          - exp_labels:
              alertname: RHACSFleetshardOperatorContainerDown
              container: kube-rbac-proxy
              namespace: rhacs
              pod: rhacs-operator-controller-manager-1234
              severity: critical
            exp_annotations:
              summary: "Fleetshard operator container `rhacs-operator-controller-manager-1234/kube-rbac-proxy` in namespace `rhacs` is down or in a CrashLoopBackOff status."
              description: "Fleetshard operator container `rhacs-operator-controller-manager-1234/kube-rbac-proxy` in namespace `rhacs` has been down or in a CrashLoopBackOff status for at least 5 minutes."
              sop_url: ""
