rule_files:
  - /tmp/prometheus-rules-test.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: kube_node_role{node="worker-1", role="worker"}
        values: "1"
      - series: kube_node_labels{node="worker-1", label_failure_domain_beta_kubernetes_io_zone="us-east-1a"}
        values: "1"
      - series: kube_node_status_allocatable{node="worker-1", resource="cpu", job="kube-state-metrics"}
        values: "100"
      - series: cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{node="worker-1", resource="cpu", job="kube-state-metrics"}
        values: "81"
    alert_rule_test:
      - eval_time: 1m
        alertname: WorkerNodesByAZCPUQuotaOverCommit
        exp_alerts: []
      - eval_time: 5m
        alertname: WorkerNodesByAZCPUQuotaOverCommit
        exp_alerts:
          - exp_labels:
              alertname: WorkerNodesByAZCPUQuotaOverCommit
              availability_zone: us-east-1a
              severity: critical
            exp_annotations:
              description: "During the last 5 minutes, the average CPU request commitment on worker nodes in AZ us-east-1a was 81%. This is above the recommended threshold of 80%."
              summary: "There is a high risk of over-committing CPU resources on worker nodes in AZ us-east-1a."
              # TODO(ROX-16772) sop_url
