apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/observability-operator.rhacs-observability: ''
  name: observability-operator
  namespace: rhacs-observability
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: observability-operator
  source: observability-operator-manifests
  sourceNamespace: rhacs-observability
  startingCSV: observability-operator.v3.0.10
