secretGenerator:
  - name: additional-scrape-configs
    options:
      disableNameSuffixHash: true
    files:
      - prometheus/federation-config.yaml
resources:
  - prometheus/pod_monitors/prometheus-self-metrics.yaml
  - prometheus/pod_monitors/rhacs-cloudwatch-exporter.yaml
  - prometheus/pod_monitors/rhacs-fleetshard-sync-metrics.yaml
  - prometheus/pod_monitors/rhacs-tenant-metrics.yaml
  - prometheus/pod_monitors/rhacs-emailsender-metrics.yaml
  - prometheus/billing-rules.yaml
  - prometheus/generated/kubernetes-mixin-alerts.yaml
  - prometheus/prometheus-rules.yaml
  - prometheus/rhacs-recording-rules.yaml
  - grafana/mixins/kubernetes/apiserver.yaml
  - grafana/mixins/kubernetes/cluster-total.yaml
  - grafana/mixins/kubernetes/controller-manager.yaml
  - grafana/mixins/kubernetes/k8s-resources-cluster.yaml
  - grafana/mixins/kubernetes/k8s-resources-namespace.yaml
  - grafana/mixins/kubernetes/k8s-resources-node.yaml
  - grafana/mixins/kubernetes/k8s-resources-pod.yaml
  - grafana/mixins/kubernetes/k8s-resources-workload.yaml
  - grafana/mixins/kubernetes/k8s-resources-workloads-namespace.yaml
  - grafana/mixins/kubernetes/kubelet.yaml
  - grafana/mixins/kubernetes/namespace-by-pod.yaml
  - grafana/mixins/kubernetes/namespace-by-workload.yaml
  - grafana/mixins/kubernetes/persistentvolumesusage.yaml
  - grafana/mixins/kubernetes/pod-total.yaml
  - grafana/mixins/kubernetes/proxy.yaml
  - grafana/mixins/kubernetes/scheduler.yaml
  - grafana/mixins/kubernetes/workload-total.yaml
  - grafana/generated/dashboards/rhacs-autoscaler.yaml
  - grafana/generated/dashboards/rhacs-central.yaml
  - grafana/generated/dashboards/rhacs-central-release.yaml
  - grafana/generated/dashboards/rhacs-central-slo.yaml
  - grafana/generated/dashboards/rhacs-cluster-overview.yaml
  - grafana/generated/dashboards/rhacs-cluster-resource-adjustment.yaml
  - grafana/generated/dashboards/rhacs-emailsender.yaml
