apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rhacs
  name: rhacs-billing-rules
spec:
  groups:
    - name: rhacs-cluster-billing
      rules:
        - expr: |
            sum(avg_over_time(rox_central_cluster_metrics_cpu_capacity{ClusterID!=""}[1h])) by(ClusterID)
          record: "rhacs:rox_central_cluster_metrics_cpu_capacity:avg_over_time1h"
