apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  labels:
    app: rhacs
    app.kubernetes.io/managed-by: observability-operator
  name: rhacs-billing-rules
spec:
  groups:
    - name: rhacs-cluster-billing
      rules:
        - expr: |
            label_replace(
              sum by (rhacs_instance_id) (
                avg by (ClusterID, rhacs_instance_id) (
                  avg_over_time(rox_central_cluster_metrics_cpu_capacity{ClusterID!=""}[1h])
                )
              ),
              "_id", "$1", "rhacs_instance_id", "(.*)"
            )
          record: "rhacs:rox_central_cluster_metrics_cpu_capacity:avg_over_time1h"
