match[]:
  - :node_memory_MemAvailable_bytes:sum
  - aggregator_unavailable_apiservice
  - aggregator_unavailable_apiservice_total
  - apiserver_request:availability30d
  - apiserver_request:burnrate1d
  - apiserver_request:burnrate1h
  - apiserver_request:burnrate2h
  - apiserver_request:burnrate30m
  - apiserver_request:burnrate3d
  - apiserver_request:burnrate5m
  - apiserver_request:burnrate6h
  - apiserver_request_terminations_total
  - apiserver_request_total
  - cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits
  - cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests
  - cluster:namespace:pod_memory:active:kube_pod_container_resource_limits
  - cluster:namespace:pod_memory:active:kube_pod_container_resource_requests
  - cluster:node_cpu:ratio_rate5m
  - cluster_quantile:apiserver_request_slo_duration_seconds:histogram_quantile
  - code_resource:apiserver_request_total:rate5m
  - container_cpu_cfs_periods_total
  - container_cpu_cfs_throttled_periods_total
  - container_cpu_usage_seconds_total
  - container_fs_reads_bytes_total
  - container_fs_reads_total
  - container_fs_writes_bytes_total
  - container_fs_writes_total
  - container_memory_cache
  - container_memory_max_usage_bytes
  - container_memory_rss
  - container_memory_swap
  - container_memory_working_set_bytes
  - container_network_receive_bytes_total
  - container_network_receive_packets_dropped_total
  - container_network_receive_packets_total
  - container_network_transmit_bytes_total
  - container_network_transmit_packets_dropped_total
  - container_network_transmit_packets_total
  - container_spec_cpu_period
  - container_spec_cpu_quota
  - container_spec_memory_limit_bytes
  - go_gc_duration_seconds
  - go_goroutines
  - go_memstats_alloc_bytes
  - go_memstats_heap_inuse_bytes
  - go_memstats_stack_inuse_bytes
  - grpc_server_handled_total
  - grpc_server_handling_seconds_bucket
  - grpc_server_started_total
  - haproxy_backend_http_responses_total
  - http_incoming_request_duration_histogram_seconds_bucket
  - http_incoming_requests_total
  - kube_daemonset_status_current_number_scheduled
  - kube_daemonset_status_desired_number_scheduled
  - kube_daemonset_status_number_available
  - kube_daemonset_status_number_misscheduled
  - kube_daemonset_status_updated_number_scheduled
  - kube_deployment_metadata_generation
  - kube_deployment_spec_replicas
  - kube_deployment_status_condition
  - kube_deployment_status_observed_generation
  - kube_deployment_status_replicas_available
  - kube_deployment_status_replicas_ready
  - kube_deployment_status_replicas_updated
  - kube_horizontalpodautoscaler_spec_max_replicas
  - kube_horizontalpodautoscaler_spec_min_replicas
  - kube_horizontalpodautoscaler_status_current_replicas
  - kube_horizontalpodautoscaler_status_desired_replicas
  - kube_job_failed
  - kube_job_status_active
  - kube_job_status_start_time
  - kube_namespace_status_phase
  - kube_node_info
  - kube_node_labels
  - kube_node_role
  - kube_node_spec_taint
  - kube_node_status_allocatable
  - kube_node_status_capacity
  - kube_node_status_condition
  - kube_persistentvolume_status_phase
  - kube_persistentvolumeclaim_access_mode
  - kube_persistentvolumeclaim_labels
  - kube_pod_container_resource_limits
  - kube_pod_container_resource_requests
  - kube_pod_container_status_ready
  - kube_pod_container_status_restarts_total
  - kube_pod_container_status_waiting_reason
  - kube_pod_info
  - kube_pod_labels
  - kube_pod_owner
  - kube_pod_status_phase
  - kube_resourcequota
  - kube_statefulset_metadata_generation
  - kube_statefulset_replicas
  - kube_statefulset_status_current_revision
  - kube_statefulset_status_observed_generation
  - kube_statefulset_status_replicas
  - kube_statefulset_status_replicas_ready
  - kube_statefulset_status_replicas_updated
  - kube_statefulset_status_update_revision
  - kubelet_certificate_manager_client_expiration_renew_errors
  - kubelet_cgroup_manager_duration_seconds_bucket
  - kubelet_cgroup_manager_duration_seconds_count
  - kubelet_node_config_error
  - kubelet_node_name
  - kubelet_pleg_relist_duration_seconds_bucket
  - kubelet_pleg_relist_duration_seconds_count
  - kubelet_pleg_relist_interval_seconds_bucket
  - kubelet_pod_start_duration_seconds_bucket
  - kubelet_pod_start_duration_seconds_count
  - kubelet_pod_worker_duration_seconds_bucket
  - kubelet_pod_worker_duration_seconds_count
  - kubelet_running_container_count
  - kubelet_running_containers
  - kubelet_running_pod_count
  - kubelet_running_pods
  - kubelet_runtime_operations_duration_seconds_bucket
  - kubelet_runtime_operations_errors_total
  - kubelet_runtime_operations_total
  - kubelet_server_expiration_renew_errors
  - kubelet_volume_stats_available_bytes
  - kubelet_volume_stats_capacity_bytes
  - kubelet_volume_stats_inodes
  - kubelet_volume_stats_inodes_free
  - kubelet_volume_stats_inodes_used
  - kubelet_volume_stats_used_bytes
  - kubeproxy_network_programming_duration_seconds_bucket
  - kubeproxy_network_programming_duration_seconds_count
  - kubeproxy_sync_proxy_rules_duration_seconds_bucket
  - kubeproxy_sync_proxy_rules_duration_seconds_count
  - kubernetes_build_info
  - namespace_cpu:kube_pod_container_resource_limits:sum
  - namespace_cpu:kube_pod_container_resource_requests:sum
  - namespace_memory:kube_pod_container_resource_limits:sum
  - namespace_memory:kube_pod_container_resource_requests:sum
  - namespace_workload_pod:kube_pod_owner:relabel
  - node_memory_MemTotal_bytes
  - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
  - node_namespace_pod_container:container_memory_cache
  - node_namespace_pod_container:container_memory_rss
  - node_namespace_pod_container:container_memory_swap
  - node_namespace_pod_container:container_memory_working_set_bytes
  - node_netstat_TcpExt_TCPSynRetrans
  - node_netstat_Tcp_OutSegs
  - node_netstat_Tcp_RetransSegs
  - node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
  - obs_operator:prometheus_remote_storage_succeeded_samples:ratio_rate1h
  - process_cpu_seconds_total
  - process_resident_memory_bytes
  - prometheus_remote_storage_samples_failed_total
  - prometheus_remote_storage_samples_retried_total
  - prometheus_remote_storage_samples_total
  - rest_client_request_duration_seconds_bucket
  - rest_client_requests_total
  - scheduler_binding_duration_seconds_bucket
  - scheduler_binding_duration_seconds_count
  - scheduler_e2e_scheduling_duration_seconds_bucket
  - scheduler_e2e_scheduling_duration_seconds_count
  - scheduler_scheduling_algorithm_duration_seconds_bucket
  - scheduler_scheduling_algorithm_duration_seconds_count
  - scheduler_volume_scheduling_duration_seconds_bucket
  - scheduler_volume_scheduling_duration_seconds_count
  - storage_operation_duration_seconds_bucket
  - storage_operation_duration_seconds_count
  - storage_operation_errors_total
  - up
  - volume_manager_total_volumes
  - workqueue_adds_total
  - workqueue_depth
  - workqueue_queue_duration_seconds_bucket
  - container_memory_usage_bytes
