- job_name: openshift-monitoring-federation
  honor_labels: true
  kubernetes_sd_configs:
    - role: service
      namespaces:
        names:
          - openshift-monitoring
  scrape_interval: 120s
  scrape_timeout: 60s
  metrics_path: /federate
  relabel_configs:
    - action: keep
      source_labels: ['__meta_kubernetes_service_name']
      regex: prometheus-k8s
    - action: keep
      source_labels: ['__meta_kubernetes_service_port_name']
      regex: web
  params:
    match[]:
      - :node_memory_MemAvailable_bytes:sum{job!~"central|scanner"}
      - aggregator_unavailable_apiservice_total{job!~"central|scanner"}
      - aggregator_unavailable_apiservice{job!~"central|scanner"}
      - apiserver_request:availability30d{job!~"central|scanner"}
      - apiserver_request:burnrate1d{job!~"central|scanner"}
      - apiserver_request:burnrate1h{job!~"central|scanner"}
      - apiserver_request:burnrate2h{job!~"central|scanner"}
      - apiserver_request:burnrate30m{job!~"central|scanner"}
      - apiserver_request:burnrate3d{job!~"central|scanner"}
      - apiserver_request:burnrate5m{job!~"central|scanner"}
      - apiserver_request:burnrate6h{job!~"central|scanner"}
      - apiserver_request_terminations_total{job!~"central|scanner"}
      - apiserver_request_total{job!~"central|scanner"}
      - cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{job!~"central|scanner"}
      - cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{job!~"central|scanner"}
      - cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{job!~"central|scanner"}
      - cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{job!~"central|scanner"}
      - cluster:node_cpu:ratio_rate5m{job!~"central|scanner"}
      - cluster_autoscaler_cluster_safe_to_autoscale{job!~"central|scanner"}
      - cluster_autoscaler_evicted_pods_total{job!~"central|scanner"}
      - cluster_autoscaler_last_activity{job!~"central|scanner"}
      - cluster_autoscaler_nodes_count{job!~"central|scanner"}
      - cluster_autoscaler_scaled_down_nodes_total{job!~"central|scanner"}
      - cluster_autoscaler_scaled_up_nodes_total{job!~"central|scanner"}
      - cluster_autoscaler_skipped_scale_events_count{job!~"central|scanner"}
      - cluster_autoscaler_unneeded_nodes_count{job!~"central|scanner"}
      - cluster_autoscaler_unschedulable_pods_count{job!~"central|scanner"}
      - cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile{job!~"central|scanner"}
      - code_resource:apiserver_request_total:rate5m{job!~"central|scanner"}
      - container_cpu_cfs_periods_total{job!~"central|scanner"}
      - container_cpu_cfs_throttled_periods_total{job!~"central|scanner"}
      - container_cpu_usage_seconds_total{job!~"central|scanner"}
      - container_fs_reads_bytes_total{job!~"central|scanner"}
      - container_fs_reads_total{job!~"central|scanner"}
      - container_fs_writes_bytes_total{job!~"central|scanner"}
      - container_fs_writes_total{job!~"central|scanner"}
      - container_memory_cache{job!~"central|scanner"}
      - container_memory_max_usage_bytes{job!~"central|scanner"}
      - container_memory_rss{job!~"central|scanner"}
      - container_memory_swap{job!~"central|scanner"}
      - container_memory_working_set_bytes{job!~"central|scanner"}
      - container_network_receive_bytes_total{job!~"central|scanner"}
      - container_network_receive_packets_dropped_total{job!~"central|scanner"}
      - container_network_receive_packets_total{job!~"central|scanner"}
      - container_network_transmit_bytes_total{job!~"central|scanner"}
      - container_network_transmit_packets_dropped_total{job!~"central|scanner"}
      - container_network_transmit_packets_total{job!~"central|scanner"}
      - container_spec_memory_limit_bytes{job!~"central|scanner"}
      - go_gc_duration_seconds{job!~"central|scanner"}
      - go_goroutines{job!~"central|scanner"}
      - go_memstats_alloc_bytes{job!~"central|scanner"}
      - go_memstats_heap_inuse_bytes{job!~"central|scanner"}
      - go_memstats_stack_inuse_bytes{job!~"central|scanner"}
      - grpc_server_handled_total{job!~"central|scanner"}
      - grpc_server_handling_seconds_bucket{job!~"central|scanner"}
      - grpc_server_started_total{job!~"central|scanner"}
      - haproxy_backend_http_responses_total{job!~"central|scanner"}
      - http_incoming_request_duration_histogram_seconds_bucket{job!~"central|scanner"}
      - http_incoming_requests_total{job!~"central|scanner"}
      - kube_daemonset_status_current_number_scheduled{job!~"central|scanner"}
      - kube_daemonset_status_desired_number_scheduled{job!~"central|scanner"}
      - kube_daemonset_status_number_available{job!~"central|scanner"}
      - kube_daemonset_status_number_misscheduled{job!~"central|scanner"}
      - kube_daemonset_status_updated_number_scheduled{job!~"central|scanner"}
      - kube_deployment_metadata_generation{job!~"central|scanner"}
      - kube_deployment_spec_replicas{job!~"central|scanner"}
      - kube_deployment_status_condition{job!~"central|scanner"}
      - kube_deployment_status_observed_generation{job!~"central|scanner"}
      - kube_deployment_status_replicas_available{job!~"central|scanner"}
      - kube_deployment_status_replicas_ready{job!~"central|scanner"}
      - kube_deployment_status_replicas_updated{job!~"central|scanner"}
      - kube_horizontalpodautoscaler_spec_max_replicas{job!~"central|scanner"}
      - kube_horizontalpodautoscaler_spec_min_replicas{job!~"central|scanner"}
      - kube_horizontalpodautoscaler_status_current_replicas{job!~"central|scanner"}
      - kube_horizontalpodautoscaler_status_desired_replicas{job!~"central|scanner"}
      - kube_job_failed{job!~"central|scanner"}
      - kube_job_status_active{job!~"central|scanner"}
      - kube_job_status_start_time{job!~"central|scanner"}
      - kube_namespace_status_phase{job!~"central|scanner"}
      - kube_node_info{job!~"central|scanner"}
      - kube_node_labels{job!~"central|scanner"}
      - kube_node_role{job!~"central|scanner"}
      - kube_node_spec_taint{job!~"central|scanner"}
      - kube_node_status_allocatable{job!~"central|scanner"}
      - kube_node_status_capacity{job!~"central|scanner"}
      - kube_node_status_condition{job!~"central|scanner"}
      - kube_persistentvolume_status_phase{job!~"central|scanner"}
      - kube_persistentvolumeclaim_access_mode{job!~"central|scanner"}
      - kube_persistentvolumeclaim_labels{job!~"central|scanner"}
      - kube_pod_container_resource_limits{job!~"central|scanner"}
      - kube_pod_container_resource_requests{job!~"central|scanner"}
      - kube_pod_container_status_ready{job!~"central|scanner"}
      - kube_pod_container_status_restarts_total{job!~"central|scanner"}
      - kube_pod_container_status_waiting_reason{job!~"central|scanner"}
      - kube_pod_info{job!~"central|scanner"}
      - kube_pod_labels{job!~"central|scanner"}
      - kube_pod_owner{job!~"central|scanner"}
      - kube_pod_status_phase{job!~"central|scanner"}
      - kube_resourcequota{job!~"central|scanner"}
      - kube_statefulset_metadata_generation{job!~"central|scanner"}
      - kube_statefulset_replicas{job!~"central|scanner"}
      - kube_statefulset_status_current_revision{job!~"central|scanner"}
      - kube_statefulset_status_observed_generation{job!~"central|scanner"}
      - kube_statefulset_status_replicas_ready{job!~"central|scanner"}
      - kube_statefulset_status_replicas_updated{job!~"central|scanner"}
      - kube_statefulset_status_replicas{job!~"central|scanner"}
      - kube_statefulset_status_update_revision{job!~"central|scanner"}
      - kubelet_certificate_manager_client_expiration_renew_errors{job!~"central|scanner"}
      - kubelet_cgroup_manager_duration_seconds_bucket{job!~"central|scanner"}
      - kubelet_cgroup_manager_duration_seconds_count{job!~"central|scanner"}
      - kubelet_node_config_error{job!~"central|scanner"}
      - kubelet_node_name{job!~"central|scanner"}
      - kubelet_pleg_relist_duration_seconds_bucket{job!~"central|scanner"}
      - kubelet_pleg_relist_duration_seconds_count{job!~"central|scanner"}
      - kubelet_pleg_relist_interval_seconds_bucket{job!~"central|scanner"}
      - kubelet_pod_start_duration_seconds_bucket{job!~"central|scanner"}
      - kubelet_pod_start_duration_seconds_count{job!~"central|scanner"}
      - kubelet_pod_worker_duration_seconds_bucket{job!~"central|scanner"}
      - kubelet_pod_worker_duration_seconds_count{job!~"central|scanner"}
      - kubelet_running_containers{job!~"central|scanner"}
      - kubelet_running_pods{job!~"central|scanner"}
      - kubelet_runtime_operations_duration_seconds_bucket{job!~"central|scanner"}
      - kubelet_runtime_operations_errors_total{job!~"central|scanner"}
      - kubelet_runtime_operations_total{job!~"central|scanner"}
      - kubelet_server_expiration_renew_errors{job!~"central|scanner"}
      - kubelet_volume_stats_available_bytes{job!~"central|scanner"}
      - kubelet_volume_stats_capacity_bytes{job!~"central|scanner"}
      - kubelet_volume_stats_inodes_free{job!~"central|scanner"}
      - kubelet_volume_stats_inodes_used{job!~"central|scanner"}
      - kubelet_volume_stats_inodes{job!~"central|scanner"}
      - kubelet_volume_stats_used_bytes{job!~"central|scanner"}
      - kubeproxy_network_programming_duration_seconds_bucket{job!~"central|scanner"}
      - kubeproxy_network_programming_duration_seconds_count{job!~"central|scanner"}
      - kubeproxy_sync_proxy_rules_duration_seconds_bucket{job!~"central|scanner"}
      - kubeproxy_sync_proxy_rules_duration_seconds_count{job!~"central|scanner"}
      - kubernetes_build_info{job!~"central|scanner"}
      - namespace_cpu:kube_pod_container_resource_limits:sum{job!~"central|scanner"}
      - namespace_cpu:kube_pod_container_resource_requests:sum{job!~"central|scanner"}
      - namespace_memory:kube_pod_container_resource_limits:sum{job!~"central|scanner"}
      - namespace_memory:kube_pod_container_resource_requests:sum{job!~"central|scanner"}
      - namespace_workload_pod:kube_pod_owner:relabel{job!~"central|scanner"}
      - network_policy_denials_sample_count{job!~"central|scanner"}
      - node_memory_MemTotal_bytes{job!~"central|scanner"}
      - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{job!~"central|scanner"}
      - node_namespace_pod_container:container_memory_cache{job!~"central|scanner"}
      - node_namespace_pod_container:container_memory_rss{job!~"central|scanner"}
      - node_namespace_pod_container:container_memory_swap{job!~"central|scanner"}
      - node_namespace_pod_container:container_memory_working_set_bytes{job!~"central|scanner"}
      - node_netstat_TcpExt_TCPSynRetrans{job!~"central|scanner"}
      - node_netstat_Tcp_OutSegs{job!~"central|scanner"}
      - node_netstat_Tcp_RetransSegs{job!~"central|scanner"}
      - node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile{job!~"central|scanner"}
      - obs_operator:prometheus_remote_storage_succeeded_samples:ratio_rate1h{job!~"central|scanner"}
      - openshift_apiserver_build_info
      - process_cpu_seconds_total{job!~"central|scanner"}
      - process_resident_memory_bytes{job!~"central|scanner"}
      - prometheus_remote_storage_samples_failed_total{job!~"central|scanner"}
      - prometheus_remote_storage_samples_retried_total{job!~"central|scanner"}
      - prometheus_remote_storage_samples_total{job!~"central|scanner"}
      - rest_client_request_duration_seconds_bucket{job!~"central|scanner"}
      - rest_client_requests_total{job!~"central|scanner"}
      - scheduler_binding_duration_seconds_bucket{job!~"central|scanner"}
      - scheduler_binding_duration_seconds_count{job!~"central|scanner"}
      - scheduler_e2e_scheduling_duration_seconds_bucket{job!~"central|scanner"}
      - scheduler_e2e_scheduling_duration_seconds_count{job!~"central|scanner"}
      - scheduler_scheduling_algorithm_duration_seconds_bucket{job!~"central|scanner"}
      - scheduler_scheduling_algorithm_duration_seconds_count{job!~"central|scanner"}
      - scheduler_volume_scheduling_duration_seconds_bucket{job!~"central|scanner"}
      - scheduler_volume_scheduling_duration_seconds_count{job!~"central|scanner"}
      - selinux_denials_sample_count{job!~"central|scanner"}
      - storage_operation_duration_seconds_bucket{job!~"central|scanner"}
      - storage_operation_duration_seconds_count{job!~"central|scanner"}
      - storage_operation_errors_total{job!~"central|scanner"}
      - up{job!~"central|scanner"}
      - volume_manager_total_volumes{job!~"central|scanner"}
      - workqueue_adds_total{job!~"central|scanner"}
      - workqueue_depth{job!~"central|scanner"}
      - workqueue_queue_duration_seconds_bucket{job!~"central|scanner"}
