{
 "title": "RHACS Dataplane - Cluster Metrics",
 "tags": [ "rhacs" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organisation",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_name)"
    }
   },
   {
    "name": "org_id",
    "label": "Organisation ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_id)"
    }
   },
   {
    "name": "instance_id",
    "label": "Central",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id=~\"$org_id\",cluster_id=~\"$cluster_id\"}, rhacs_instance_id)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Central Count",
   "type": "timeseries",
   "description": "The number of Central deployments with at least one pod in ready state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(clamp_max(count by (namespace) (kube_pod_container_status_ready{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kube-state-metrics\"}), 1))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Central Count By Organisation",
   "type": "timeseries",
   "description": "The number of Central deployments with at least one pod in ready state per organisation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (rhacs_org_name) (clamp_max(count by (namespace) (kube_pod_container_status_ready{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kube-state-metrics\"}), 1) * on(namespace) group_left(rhacs_org_name) count by (namespace, rhacs_org_name) (process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=\"central\", rhacs_org_id=~\"$org_id\"}))",
     "legendFormat": "{{rhacs_org_name}}"
    }
   ]
  },
  {
   "title": "Total Secured Cores / Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum(rox_central_cluster_metrics_node_count{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Secured Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) by (namespace)",
     "legendFormat": "{{rhacs_instance_id}}"
    }
   ]
  },
  {
   "title": "Paused Reconcile Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(max by (exported_instance) (acs_fleetshard_pause_reconcile_instances == 1)) or vector(0)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Secured Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"} > 0) or vector(0)",
     "legendFormat": "Clusters"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Central Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Cluster Violations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "SELinux Violations per minute",
   "type": "timeseries",
   "description": "Shows the SELinux AVC Denials per minute, as logged to CloudWatch.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "selinux_denials_sample_count", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "description": "\n",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 43 },
   "options": {
    "content": "### Description\n\nThis graph shows the occurences per minute of **SELinux AVC denials** on the cluster.\nThese violations are logged on the cluster, propagated to CloudWatch, aggregated by a log metric, retrieved by the cloudwatch-exporter and finally scraped by Prometheus.\n\n**Expected: 0 violations.**\n\nA violation means that the cluster node's SELinux policy prevented a process' actions.\nAs an example, a violation could indicate that a process on the cluster tried to access a file which is SELinux-protected.\n\n### Drill-Down\n\nLog into the cluster's AWS account and use a [Log Insights query](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40logStream*20like*20*2flinux-audit*2f*0a*7c*20filter*20*40message*20like*20*2fAVC*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*201000~source~(~))) similar to this one:\n```\nfields @timestamp, @message, @logStream, @log\n| filter @logStream like /linux-audit/\n| filter @message like /AVC/\n| sort @timestamp desc\n| limit 1000\n```\n\n**Note:**\n* all CloudWatch related resources are located in the `us-east-1` region.\n* the log group containing the violation logs are called `acs-<cluster name>.audit`.\n"
   }
  },
  {
   "title": "Network Policy Violations per minute",
   "type": "timeseries",
   "description": "Shows the Network Policy ACL Denials per minute, as logged to CloudWatch.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_policy_denials_sample_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "\n",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 51 },
   "options": {
    "content": "### Description\n\nThis graph shows the occurences per minute of Network Policy ACL denials on the cluster.\nThese violations are logged on the cluster, propagated to CloudWatch, aggregated by a log metric, retrieved by the cloudwatch-exporter and finally scraped by Prometheus.\n\n**Expected: 0 violations.**\n\nA violation means that network traffic was prevented due to a Kubernetes Network Policy.\nAs an example, a violation could indicate that communication between RHACS tenant namespaces\nwas attempted, which is strictly forbidden.\n\n### Drill-Down\n\nLog into the cluster's AWS account and use a [Log Insights query](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*2facl_log*28.*2a*29.*2a*5csverdict*3ddrop*2f*0a*7c*20filter*20*40logStream*20like*20*2f.*2aovn-audit*5c.log*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*201000~source~(~))) similar to this one:\n```\nfields @timestamp, @message, @logStream, @log\n| filter @message like /acl_log(.*).*\\sverdict=drop/\n| filter @logStream like /.*ovn-audit\\.log/\n| sort @timestamp desc\n| limit 1000\n```\n\n**Note:**\n* all CloudWatch related resources are located in the `us-east-1` region.\n* the log group containing the violation logs are called `acs-<cluster name>.audit`.\n\n"
   }
  },
  { "title": "Instance Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Central Overview Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rox_central_secured_vcpus{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace, rhacs_org_name, rhacs_org_id, rhacs_version, rhacs_expired_at)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"central-.*\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"central-.*\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "clamp_max(label_replace(acs_fleetshard_pause_reconcile_instances, \"namespace\", \"rhacs-$1\", \"exported_instance\", \"(.*)\"), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scanner Overview Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"rhacs-$instance_id\", job=\"kubelet\", container=\"scanner\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"rhacs-$instance_id\", job=\"kubelet\", container=\"scanner\"}[$__range])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"rhacs-$instance_id\", job=\"kubelet\", container=\"matcher\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"rhacs-$instance_id\", job=\"kubelet\", container=\"matcher\"}[$__range])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"scanner\"}) by (namespace, rhacs_org_name, rhacs_version)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"rhacs-$instance_id\", job=\"kubelet\", container=\"indexer\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"rhacs-$instance_id\", job=\"kubelet\", container=\"indexer\"}[$__range])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scans per Day by Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(rox_central_scan_duration_count[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Certificate Expiry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Certificates Expiry",
   "type": "table",
   "description": "Expiration dates for central and scanner TLS certificates.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "acs_fleetshard_certificate_expiration_timestamp *\non (exported_namespace)\ngroup_left(rhacs_org_name)\nlabel_replace((sum(rox_central_info) by (rhacs_org_name, namespace) * 0 + 1), \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}