{
 "title": "RHACS Consolidated Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\"}, cluster_id)"
    }
   },
   {
    "name": "org_name",
    "label": "Organisation",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_id!=\"16536854\", cluster_id=~\"$cluster_id\"}, rhacs_org_name)"
    }
   },
   {
    "name": "org_id",
    "label": "Organisation ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id!=\"16536854\", cluster_id=~\"$cluster_id\"}, rhacs_org_id)"
    }
   },
   {
    "name": "instance_id",
    "label": "Central",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id=~\"$org_id\", cluster_id=~\"$cluster_id\"}, rhacs_instance_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "acs-fleet-manager-stage,acs-fleet-manager-production,None"
   }
  ]
 },
 "panels": [
  {
   "title": "Dataplane Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Plane Cluster Count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (cluster_id) (process_cpu_seconds_total{job=\"central\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Central Count by Cluster",
     "type": "timeseries",
     "description": "The number of Central deployments with at least one pod in ready state.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(clamp_max(count by (namespace) (kube_pod_container_status_ready{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kube-state-metrics\"}), 1))",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Central Count by Organisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "count by (rhacs_org_name) (clamp_max(count by (namespace) (kube_pod_container_status_ready{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kube-state-metrics\"}), 1) * on(namespace) group_left(rhacs_org_name) count by (namespace, rhacs_org_name) (process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=\"central\", rhacs_org_id=~\"$org_id\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Secured Cores / Nodes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
       "legendFormat": "Cores"
      },
      {
       "expr": "sum(rox_central_cluster_metrics_node_count{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Secured Cores",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) by (namespace)",
       "legendFormat": "{{rhacs_instance_id}}"
      }
     ]
    },
    {
     "title": "Cluster Resource Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster_id=~\"$cluster_id\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster_id=~\"$cluster_id\"})",
       "legendFormat": "CPU Request"
      },
      {
       "expr": "cluster:node_cpu:ratio_rate5m{cluster_id=~\"$cluster_id\"}",
       "legendFormat": "CPU Utilisation"
      },
      {
       "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster_id=~\"$cluster_id\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster_id=~\"$cluster_id\"})",
       "legendFormat": "Memory Request"
      },
      {
       "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
       "legendFormat": "Memory Utilisation"
      }
     ]
    },
    {
     "title": "Central Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Central Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"rhacs-$instance_id\", persistentvolumeclaim=\"stackrox-db\", job=~\"kubelet\"}) by (namespace) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"rhacs-$instance_id\", persistentvolumeclaim=\"stackrox-db\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
     "options": {
      "content": "```\nPlease Select Particular Cluster for Central overview and Scanner Overview Tables\n```"
     }
    },
    {
     "title": "Central Overview Table",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace, rhacs_org_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"rhacs-$instance_id\", container=\"central\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"central-.*\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"central-.*\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "min(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace, rhacs_version)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scanner Overview Table",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"rhacs-$instance_id\", container=\"scanner\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"scanner\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"scanner-.*\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"scanner-.*\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}[$__range])) by (namespace) /\nsum(container_spec_cpu_quota{namespace=~\"rhacs-$instance_id\", container=\"scanner\"} / container_spec_cpu_period{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}[$__range])) by (namespace) / sum(increase(container_cpu_cfs_periods_total{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"scanner\"}) by (namespace, rhacs_org_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataplane Central SLO Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 23, "x": 0, "y": 2 },
     "options": {
      "content": "## Definition\n\nThe availability of Central is defined as a combination of pod ready status and API error rate.\n\n`Availability SLI = Pod Ready SLI * Error Rate SLI`\n\nThe SLO target is 99% availability calculated over 28 day rolling intervals."
     }
    },
    {
     "title": "SLO count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} <= 1 and central:sli:availability{rhacs_instance_id=~\"$instance_id\"}) or vector(0)",
       "legendFormat": "OK"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} > 1 and central:sli:availability{rhacs_instance_id=~\"$instance_id\"}) or vector(0)",
       "legendFormat": "MISS"
      }
     ]
    },
    {
     "title": "Error Budget Exhaustion [28d]",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} < 0.5 and central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "x < 0.5"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} >= 0.5 and central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} < 0.7 and central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "0.5 < x < 0.7"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} >= 0.7 and central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} < 1  and central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "0.7 < x < 1"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} >= 1 and central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "x > 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataplane Central SLO Table View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLOs",
     "type": "table",
     "description": "Probe instances are excluded from the table.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "central:sli:availability:extended_avg_over_time28d{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} and central:sli:availability{rhacs_instance_id=~\"$instance_id\"}",
       "legendFormat": "xx"
      },
      {
       "expr": "sum by (rhacs_instance_id) (central:slo:availability:error_budget_exhaustion{rhacs_org_id!=\"16536854\",rhacs_instance_id=~\"$instance_id\"} and central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataplane Central SLOs By Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 4 },
     "options": {
      "content": "Select instances via the variables on top of the dashbord. If multiple Centrals are selected, the SLIs/SLOs are averaged."
     }
    },
    {
     "title": "Availability SLO [28d]",
     "type": "gauge",
     "description": "Target: `99%`",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(central:sli:availability:extended_avg_over_time28d{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Availability SLI",
     "type": "timeseries",
     "description": "`Pod Ready SLI * Error Rate SLI`",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Pod Ready SLI",
     "type": "timeseries",
     "description": "`1` is at least one pod is in ready state. `0` otherwise.",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:sli:pod_ready{namespace=~\"rhacs-$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Error Rate SLI",
     "type": "timeseries",
     "description": "`1` if the combined error rate of gRPC and HTTP requests is `<35%`. `0` otherwise.\n\nA gRPC error is defined by a response with `grpc_code != OK`. An HTTP error is defined by a response with status code `5xx`.",
     "gridPos": { "h": 8, "w": 6, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:sli:error_rate{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Error Budget Exhaustion [28d]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Budget Exhaustion [28d]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 5, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Burn Rate [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 14, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(central:slo:availability:burnrate1h{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  }
 ]
}