{
 "title": "RHACS Consolidated Dashboard",
 "tags": [ "rhacs" ],
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organisation",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_name)"
    }
   },
   {
    "name": "org_id",
    "label": "Organisation ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_id)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id=~\"$org_id\",cluster_id=~\"$cluster_id\"}, rhacs_instance_id)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Central SLO Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 121 },
     "options": {
      "content": "## Definition\n\nThe availability of Central is defined as a combination of pod ready status and API error rate.\n\n`Availability SLI = Pod Ready SLI * Error Rate SLI`\n\nThe SLO target is 99% availability calculated over 28 day rolling intervals."
     }
    },
    {
     "title": "SLO count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 126 },
     "targets": [
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} <= 1 and central:sli:availability) or vector(0)",
       "legendFormat": "OK"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} > 1 and central:sli:availability) or vector(0)",
       "legendFormat": "MISS"
      }
     ]
    },
    {
     "title": "Error Budget Exhaustion [28d]",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 126 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} < 0.5 and central:sli:availability)",
       "legendFormat": "x < 0.5"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} >= 0.5 and central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} < 0.7 and central:sli:availability)",
       "legendFormat": "0.5 < x < 0.7"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} >= 0.7 and central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} < 1  and central:sli:availability)",
       "legendFormat": "0.7 < x < 1"
      },
      {
       "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} >= 1 and central:sli:availability)",
       "legendFormat": "x > 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Central SLO Table View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLOs",
     "type": "table",
     "description": "Probe instances are excluded from the table.",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "central:sli:availability:extended_avg_over_time28d{rhacs_instance_id=~\"$instance_id\"} and central:sli:availability",
       "legendFormat": "xx"
      },
      {
       "expr": "sum by (rhacs_instance_id) (central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} and central:sli:availability)",
       "legendFormat": "__auto"
      },
      {
       "expr": "process_cpu_seconds_total{rhacs_instance_id=~\"$instance_id\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Central SLO By Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 136 },
     "options": {
      "content": "Select instances via the variables on top of the dashbord. If multiple Centrals are selected, the SLIs/SLOs are averaged."
     }
    },
    {
     "title": "Availability SLO [28d]",
     "type": "gauge",
     "description": "Target: `99%`",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(central:sli:availability:extended_avg_over_time28d{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Availability SLI",
     "type": "timeseries",
     "description": "`Pod Ready SLI * Error Rate SLI`",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Pod Ready SLI",
     "type": "timeseries",
     "description": "`1` is at least one pod is in ready state. `0` otherwise.",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:sli:pod_ready{namespace=~\"rhacs-$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Error Rate SLI",
     "type": "timeseries",
     "description": "`1` if the combined error rate of gRPC and HTTP requests is `<35%`. `0` otherwise.\n\nA gRPC error is defined by a response with `grpc_code != OK`. An HTTP error is defined by a response with status code `5xx`.",
     "gridPos": { "h": 8, "w": 6, "x": 17, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:sli:error_rate{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Error Budget Exhaustion [28d]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Budget Exhaustion [28d]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 5, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Burn Rate [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 14, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(central:slo:availability:burnrate1h{rhacs_instance_id=~\"$instance_id\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics By Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Central Count",
     "type": "timeseries",
     "description": "The number of Central deployments with at least one pod in ready state.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(clamp_max(count by (namespace) (kube_pod_container_status_ready{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kube-state-metrics\"}), 1))",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Central Count By Organisation",
     "type": "timeseries",
     "description": "The number of Central deployments with at least one pod in ready state per organisation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (rhacs_org_name) (clamp_max(count by (namespace) (kube_pod_container_status_ready{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kube-state-metrics\"}), 1) * on(namespace) group_left(rhacs_org_name) count by (namespace, rhacs_org_name) (process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=\"central\", rhacs_org_id=~\"$org_id\"}))",
       "legendFormat": "{{rhacs_org_name}}"
      }
     ]
    },
    {
     "title": "Total Secured Cores / Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
       "legendFormat": "Cores"
      },
      {
       "expr": "sum(rox_central_cluster_metrics_node_count{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Secured Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) by (namespace)",
       "legendFormat": "{{rhacs_instance_id}}"
      }
     ]
    },
    {
     "title": "Paused Reconcile Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(max by (exported_instance) (acs_fleetshard_pause_reconcile_instances == 1)) or vector(0)",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Secured Clusters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\",job=~\"central\"}) or vector(0)",
       "legendFormat": "Clusters"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability Zone CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "availability_zone:strictly_worker_nodes:cpu_limit_ratio",
       "legendFormat": "Limit / {{availability_zone}}"
      },
      {
       "expr": "availability_zone:strictly_worker_nodes:cpu_request_ratio",
       "legendFormat": "Request / {{availability_zone}}"
      }
     ]
    },
    {
     "title": "Availability Zone Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "availability_zone:strictly_worker_nodes:memory_limit_ratio",
       "legendFormat": "Limit / {{availability_zone}}"
      },
      {
       "expr": "availability_zone:strictly_worker_nodes:memory_request_ratio",
       "legendFormat": "Request / {{availability_zone}}"
      }
     ]
    },
    {
     "title": "Central Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Central Overview Table",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"central\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rox_central_cluster_metrics_cpu_capacity{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace, rhacs_org_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"rhacs-$instance_id\", container=\"central\"}[30m])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"central-.*\"}[5m])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"central-.*\"}[5m])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "min(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"central\"}) by (namespace, rhacs_version)",
       "legendFormat": "__auto"
      },
      {
       "expr": "clamp_max(label_replace(acs_fleetshard_pause_reconcile_instances, \"namespace\", \"rhacs-$1\", \"exported_instance\", \"(.*)\"), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scanner Overview Table",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"rhacs-$instance_id\", container=\"scanner\", job=~\"kubelet\"}) by (namespace) / sum(container_spec_memory_limit_bytes{namespace=~\"rhacs-$instance_id\", container=\"scanner\", job=~\"kubelet\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"scanner-.*\"}[5m])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rhacs-$instance_id\", job=~\"kubelet\", pod=~\"scanner-.*\"}[5m])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}[5m])) by (namespace) /\nsum(container_spec_cpu_quota{namespace=~\"rhacs-$instance_id\", container=\"scanner\"} / container_spec_cpu_period{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}[5m])) by (namespace) / sum(increase(container_cpu_cfs_periods_total{namespace=~\"rhacs-$instance_id\", container=\"scanner\"}[5m])) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(process_cpu_seconds_total{namespace=~\"rhacs-$instance_id\", job=~\"scanner\"}) by (namespace, rhacs_org_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}