{
 "title": "RHACS Dataplane - Email Sender",
 "tags": [ "rhacs" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organisation",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_name)"
    }
   },
   {
    "name": "org_id",
    "label": "Organisation ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_id)"
    }
   },
   {
    "name": "instance_id",
    "label": "Central",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id=~\"$org_id\",cluster_id=~\"$cluster_id\"}, rhacs_instance_id)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of sent emails by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(acs_emailsender_send_email_total{job=~\"emailsender\"}[5m])) by (tenant_id)",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Total emails sent by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(acs_emailsender_send_email_total{job=\"emailsender\"}) by (tenant_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of throttled email sends by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(acs_emailsender_throttled_send_email_total{job=~\"emailsender\"}[5m])) by (tenant_id)",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Rate of failed email sends by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(acs_emailsender_failed_send_email_total{job=~\"emailsender\"}[5m])) by (tenant_id)",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  }
 ]
}