apiVersion: monitoring.rhobs/v1
kind: PodMonitor
metadata:
  name: prometheus-self-metrics
  labels:
    app: rhacs
    app.kubernetes.io/managed-by: observability-operator
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: web
  selector:
    matchLabels:
      prometheus: obs-prometheus
