apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-self-metrics
  labels:
    app: rhacs
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: web
  selector:
    matchLabels:
      prometheus: obs-prometheus
