apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rhacs-scanner-metrics
  labels:
    app: rhacs
spec:
  selector:
    matchLabels:
      app: "scanner"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: monitoring
      relabelings:
        - action: labeldrop
          regex: endpoint

        - sourceLabels: [container]
          targetLabel: job

        - action: labelmap
          regex: __meta_kubernetes_pod_annotation_rhacs_redhat_com_(.+)
          replacement: rhacs_${1}

        - action: labelmap
          regex: __meta_kubernetes_pod_label_rhacs_redhat_com_(.+)
          replacement: rhacs_${1}

        - sourceLabels: [rhacs_tenant]
          targetLabel: rhacs_instance_id

        - action: labeldrop
          regex: rhacs_tenant

        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_version]
          targetLabel: rhacs_version
