apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rhacs-central-metrics
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      app: "central"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: monitoring
      relabelings:
        - action: labeldrop
          regex: endpoint
