apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rhacs-probe-metrics
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      app: "probe"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: monitoring
      relabelings:
        - action: labeldrop
          regex: endpoint

        - sourceLabels: [container]
          action: replace
          targetLabel: job
