{
 "title": "RHACS Dataplane - Central Metrics",
 "tags": [ "rhacs" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"central\"}, instance)"
   },
   { "name": "Operation", "query": "label_values(Operation)" },
   { "name": "Type", "query": "label_values(Type)" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensors",
   "type": "stat",
   "description": "Number of connected Sensors. This equals the number of secured clusters.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (ClusterID) (rox_central_cluster_metrics_node_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"} > 0))"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "gRPC success rate",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Internal\"}[$__rate_interval])) + sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unknown\"}[$__rate_interval])) + sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unavailable\"}[$__rate_interval])) + sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unimplemented\"}[$__rate_interval]))) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval]))) OR on() vector(1)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "description": "gRPC throughput",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "stat",
   "description": "gRPC 95% latency percentile",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Kubernetes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Ready",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\", container=\"central\", job=~\"kube-state-metrics\"})",
       "legendFormat": "central"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"central\", job=~\"kube-state-metrics\"}[5m]))",
       "legendFormat": "central"
      }
     ]
    },
    {
     "title": "Container Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", container=\"central\", job=~\"kubelet\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container=\"central\", job=~\"kubelet\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(container_memory_rss{namespace=\"$namespace\", container=\"central\", job=~\"kubelet\"})",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum(container_memory_swap{namespace=\"$namespace\", container=\"central\", job=~\"kubelet\"})",
       "legendFormat": "Swap"
      }
     ]
    },
    {
     "title": "Database Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"stackrox-db\", job=~\"kube-state-metrics\"})",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"stackrox-db\", job=~\"kubelet\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"stackrox-db\", job=~\"kubelet\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"stackrox-db\", job=~\"kubelet\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\".*\", job=~\"kubelet\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\".*\", job=~\"kubelet\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(process_cpu_seconds_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_alloc_bytes{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "avg(go_memstats_stack_inuse_bytes{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}) by (quantile)",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"OK\"}[$__rate_interval]))\n/ sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval]))",
       "legendFormat": "OK"
      },
      {
       "expr": "(sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"AlreadyExists\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unauthenticated\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"FailedPrecondition\"}[$__rate_interval]))\n)/ sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval]))",
       "legendFormat": "ClientError"
      },
      {
       "expr": "(sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Internal\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unknown\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unavailable\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\",grpc_code=\"Unimplemented\"}[$__rate_interval]))\n)/ sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval]))",
       "legendFormat": "ServerError"
      }
     ]
    },
    {
     "title": "Status Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (grpc_code)\n/ ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Request Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (grpc_service) \n/ ignoring(grpc_service) group_left sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency P95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (grpc_service,le)\n)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency Percentiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",code=~\"2\\\\d\\\\d\"}[$__rate_interval])) / sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",code=~\"3\\\\d\\\\d\"}[$__rate_interval])) / sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",code=~\"4\\\\d\\\\d\"}[$__rate_interval])) / sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",code=~\"5\\\\d\\\\d\"}[$__rate_interval])) / sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Status Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (code)\n/ ignoring(code) group_left sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (method,path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Request Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (method,path) \n/ ignoring(method,path) group_left sum(rate(http_incoming_requests_total{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Latency P95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(http_incoming_request_duration_histogram_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (method,path,le)\n)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Latency Percentiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, \n  sum(rate(http_incoming_request_duration_histogram_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(http_incoming_request_duration_histogram_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(http_incoming_request_duration_histogram_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.5, \n  sum(rate(http_incoming_request_duration_histogram_seconds_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "GraphQL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Duration Percentiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,  sum(rate(rox_central_graphql_query_duration_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.99,  sum(rate(rox_central_graphql_query_duration_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95,  sum(rate(rox_central_graphql_query_duration_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.50,  sum(rate(rox_central_graphql_query_duration_bucket{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Operation Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Operation) (rate(rox_central_graphql_op_duration_sum{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Operation: {{Operation}}"
      }
     ]
    },
    {
     "title": "Operation Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rox_central_graphql_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (Operation) \n/ ignoring(Operation) group_left sum(rate(rox_central_graphql_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Operation: {{Operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Billing Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Secured Cluster - Sensors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(count by (ClusterID) (rox_central_cluster_metrics_node_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"} > 0))",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Secured Cluster - Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ClusterID) (rox_central_cluster_metrics_node_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "ClusterID: {{ClusterID}}"
      }
     ]
    },
    {
     "title": "Secured Cluster - CPU Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ClusterID) (rox_central_cluster_metrics_cpu_capacity{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "ClusterID: {{ClusterID}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bolt Object Count",
     "type": "graph",
     "description": "Number of key/value pairs in each bucket.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rox_central_bolt_bucket_key_n{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{Bucket}}"
      }
     ]
    },
    {
     "title": "RocksDB Object Count",
     "type": "graph",
     "description": "RocksDB prefix size (equivalent to bolt bucket).",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rox_central_rocksdb_prefix_size{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{Prefix}}"
      }
     ]
    },
    {
     "title": "Bolt Operation Count",
     "type": "graph",
     "description": "Number of key/value pairs in each bucket.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rox_central_bolt_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "RocksDB Operation Count",
     "type": "graph",
     "description": "Number of key/value pairs in each bucket.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rox_central_rocksdb_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "Bolt Avg Operation Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rox_central_bolt_op_duration_sum{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"} / rox_central_bolt_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "RocksDB Avg Operation Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rox_central_rocksdb_op_duration_sum{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"} / rox_central_rocksdb_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "Indexer Operation Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rox_central_index_op_duration_sum{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"} / rox_central_index_op_duration_count{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\",Operation=~\"$Operation\",Type=~\"$Type\"}",
       "legendFormat": "Operation: {{Operation}}, Type: {{Type}}"
      }
     ]
    },
    {
     "title": "DB and Index Disk Consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rox_central_bolt_db_size{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Bolt"
      },
      {
       "expr": "rox_central_rocksdb_db_size{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "RocksDB"
      },
      {
       "expr": "rox_central_bleve_index_CurOnDiskBytes{namespace=\"$namespace\",job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Bleve, Index: {{Index}}"
      }
     ]
    }
   ]
  }
 ]
}