{
 "title": "RHACS Dataplane - Central SLOs",
 "tags": [ "rhacs" ],
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organisation",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_name)"
    }
   },
   {
    "name": "org_id",
    "label": "Organisation ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id!=\"16536854\",cluster_id=~\"$cluster_id\"}, rhacs_org_id)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\", rhacs_org_name=~\"$org_name\", rhacs_org_id=~\"$org_id\",cluster_id=~\"$cluster_id\"}, rhacs_instance_id)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"central\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "## Definition\n\nThe availability of Central is defined as a combination of pod ready status and API error rate.\n\n`Availability SLI = Pod Ready SLI * Error Rate SLI`\n\nThe SLO target is 99% availability calculated over 28 day rolling intervals."
   }
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SLO count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} <= 1 and central:sli:availability) or vector(0)",
     "legendFormat": "OK"
    },
    {
     "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} > 1 and central:sli:availability) or vector(0)",
     "legendFormat": "MISS"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion [28d]",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} < 0.5 and central:sli:availability)",
     "legendFormat": "x < 0.5"
    },
    {
     "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} >= 0.5 and central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} < 0.7 and central:sli:availability)",
     "legendFormat": "0.5 < x < 0.7"
    },
    {
     "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} >= 0.7 and central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} < 1  and central:sli:availability)",
     "legendFormat": "0.7 < x < 1"
    },
    {
     "expr": "count(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} >= 1 and central:sli:availability)",
     "legendFormat": "x > 1"
    }
   ]
  },
  { "title": "Table View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SLOs",
   "type": "table",
   "description": "Probe instances are excluded from the table.",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "central:sli:availability:extended_avg_over_time28d{rhacs_instance_id=~\"$instance_id\"} and central:sli:availability",
     "legendFormat": "xx"
    },
    {
     "expr": "sum by (rhacs_instance_id) (central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"} and central:sli:availability)",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_seconds_total{rhacs_instance_id=~\"$instance_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 32 },
   "options": {
    "content": "Select instances via the variables on top of the dashbord. If multiple Centrals are selected, the SLIs/SLOs are averaged."
   }
  },
  {
   "title": "Availability SLO [28d]",
   "type": "gauge",
   "description": "Target: `99%`",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(central:sli:availability:extended_avg_over_time28d{rhacs_instance_id=~\"$instance_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability SLI",
   "type": "timeseries",
   "description": "`Pod Ready SLI * Error Rate SLI`",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(central:sli:availability{rhacs_instance_id=~\"$instance_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pod Ready SLI",
   "type": "timeseries",
   "description": "`1` is at least one pod is in ready state. `0` otherwise.",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(central:sli:pod_ready{namespace=~\"rhacs-$instance_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Rate SLI",
   "type": "timeseries",
   "description": "`1` if the combined error rate of gRPC and HTTP requests is `<35%`. `0` otherwise.\n\nA gRPC error is defined by a response with `grpc_code != OK`. An HTTP error is defined by a response with status code `5xx`.",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(central:sli:error_rate{rhacs_instance_id=~\"$instance_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion [28d]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion [28d]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(central:slo:availability:error_budget_exhaustion{rhacs_instance_id=~\"$instance_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Burn Rate [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(central:slo:availability:burnrate1h{rhacs_instance_id=~\"$instance_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}