name: Sync stage -> production
on:
  workflow_dispatch:
permissions:
  # Needed to read branches.
  contents: read
  # Needed to create PR's.
  pull-requests: write
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Opening pull request
        id: pull
        uses: jdtx0/branch-sync@v1.5.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "stage"
          TO_BRANCH: "production"
          LABELS: '["automerge"]'
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
