name: Sync stage -> production
on:
  workflow_dispatch:
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Opening pull request
        id: pull
        # We need main for PULL_REQUEST_AUTO_MERGE_METHOD, which is currently not yet released.
        uses: tretuna/sync-branches@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "stage"
          TO_BRANCH: "production"
          PULL_REQUEST_AUTO_MERGE_METHOD: merge
