name: Sync master -> stage
on:
  workflow_dispatch:
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Opening pull request
        id: pull
        # Need master for LABELS option.
        uses: tretuna/sync-branches@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "stage"
          LABELS: '["automerge"]'
